HOST: http://www.google.com/

--- Lims-management-app ---

---
Welcome to our API documentation for lims-management-app. 

S2 API provides a JSON RESTful interface. The path to the root URL `/` only is needed to interact with the API.
All the other actions are embedded in every JSON response.
Please note that all URLs are to be considered unstable. As a consequence, you should only refer to the actions
elements returned in the response.

Please find below the different actions available in the JSON:

* `create` creates a new resource using a HTTP POST request
* `read`, `first` and `last` actions are used for pagination through HTTP GET requests
* `update` action update a resource using a HTTP PUT request
* `delete` action delete a resource using a HTTP DELETE request

In top of the above actions, more specific actions are available to interact between multiple resources.
These actions use generally HTTP POST request and are listed under the root JSON response.

Please note you will generally find two different URLs to create a new resource, which produce an identical result:
`/resources` or `/actions/create_resource`.
---


--
Root
--

The root JSON lists all the resources available through the lims-management-app api and all the actions which can be performed. 
A resource responds to all the actions listed under its `actions` elements.
Consider this URL and the JSON response like the entry point for lims-management-app api. All the other interactions through the 
API can be performed browsing this JSON response.
GET /
> Accept: application/json
< 200
< Content-Type: application/json
{
    "actions": {
        "read": "http://example.org/"
    },
    "samples": {
        "actions": {
            "create": "http://example.org/samples",
            "read": "http://example.org/samples",
            "first": "http://example.org/samples/page=1",
            "last": "http://example.org/samples/page=-1"
        }
    },
    "sample_collections": {
      "actions": {
        "create": "http://example.org/sample_collections",
        "read": "http://example.org/sample_collections",
        "first": "http://example.org/sample_collections/page=1",
        "last": "http://example.org/sample_collections/page=-1"
      }
    },
    "uuid_resources": {
        "actions": {
            "create": "http://example.org/uuid_resources",
            "read": "http://example.org/uuid_resources",
            "first": "http://example.org/uuid_resources/page=1",
            "last": "http://example.org/uuid_resources/page=-1"
        }
    },
    "searches": {
      "actions": {
             "create": "http://example.org/searches",
             "read": "http://example.org/searches",
             "first": "http://example.org/searches/page=1",
             "last": "http://example.org/searches/page=-1"
           }
       },
    "update_samples": {
        "actions": {
            "create": "http://example.org/actions/update_sample"
        }
    },
    "delete_samples": {
        "actions": {
            "create": "http://example.org/actions/delete_sample"
        }
    },
    "bulk_delete_samples": {
        "actions": {
            "create": "http://example.org/actions/bulk_delete_sample"
        }
    },
    "create_samples": {
        "actions": {
            "create": "http://example.org/actions/create_sample"
        }
    },
    "bulk_update_samples": {
        "actions": {
            "create": "http://example.org/actions/bulk_update_sample"
        }
    },
    "create_sample_collections": {
      "actions": {
        "create": "http://example.org/actions/create_sample_collection"
      }
    },
    "update_sample_collections": {
      "actions": {
        "create": "http://example.org/actions/update_sample_collection"
      }
    },
    "delete_sample_collections": {
      "actions": {
        "create": "http://example.org/actions/delete_sample_collection"
      }
    },
    "create_searches": {
      "actions": {
        "create": "http://example.org/actions/create_search"
      }
    },
    "multi_criteria_filters": {
      "actions": {
        "create": "http://example.org/multi_criteria_filters",
        "read": "http://example.org/multi_criteria_filters",
        "first": "http://example.org/multi_criteria_filters/page=1",
        "last": "http://example.org/multi_criteria_filters/page=-1"
      }
    },
    "revision": 3
}


--
Sample Resource
--
**Create a new sample**

* `sanger_sample_id_core` is mandatory. It is used as a prefix to generate a unique sanger sample id.
* `state` must belong to `draft`, `published`. If not set, the default state is `draft`.
* If a sample is created with the `published` state, `taxon_id`, `scientific_name`, `common_name` and `supplier_sample_name` are mandatory
* If `taxon_id` is set, it must match with `scientific_name`/`common_name`
* If `sample_type` is set, it must belong to `DNA Human`, `DNA Pathogen`, `RNA`, `Blood`, `Saliva`, `Tissue Non-Tumour`, `Tissue Tumour`, `Pathogen` or `Cell Pellet`
* If `gender` is set, it must belong to `Not applicable`, `Male`, `Female`, `Mixed`, `Hermaphrodite` or `Unknown`

See the example below to know the list of available parameters for a sample.
POST /samples
> Accept: application/json
{
    "sample": {
        "state": "draft",
        "sanger_sample_id_core": "studyX",
        "gender": "Male",
        "sample_type": "RNA",
        "taxon_id": 9606,
        "volume": 100,
        "date_of_sample_collection": "2013-04-25 10:27 UTC",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "age_band": "45-60",
        "disease_phenotype": "normal",
        "storage_conditions": "conditions",
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:05 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:05 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "English"
        }
    }
}
< 200
< Content-Type: application/json
{
    "sample": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "sanger_sample_id": "studyX-1",
        "state": "draft",
        "gender": "Male",
        "sample_type": "RNA",
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "storage_conditions": "conditions",
        "taxon_id": 9606,
        "volume": 100,
        "age_band": "45-60",
        "disease_phenotype": "normal",
        "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "English"
        }
    }
}


**Update a sample**

* If a draft sample is updated with the `published` state, `taxon_id`, `scientific_name`, `common_name` and `supplier_sample_name` needs to be set in the sample
* `taxon_id` and `scientific_name`/`common_name` must match
* `sample_type` must belong to `DNA Human`, `DNA Pathogen`, `RNA`, `Blood`, `Saliva`, `Tissue Non-Tumour`, `Tissue Tumour`, `Pathogen` or `Cell Pellet`
* `gender` must belong to `Not applicable`, `Male`, `Female`, `Mixed`, `Hermaphrodite` or `Unknown`

See the example below to know the list of available parameters for a sample.
PUT /11111111-2222-3333-4444-555555555555
> Accept: application/json
{
    "gender": "Male",
    "state": "published",
    "sample_type": "RNA",
    "taxon_id": 9606,
    "volume": 100,
    "date_of_sample_collection": "2013-04-25 10:27 UTC",
    "is_sample_a_control": true,
    "is_re_submitted_sample": false,
    "hmdmc_number": "number",
    "supplier_sample_name": "name",
    "common_name": "man",
    "scientific_name": "homo sapiens",
    "ebi_accession_number": "number",
    "sample_source": "source",
    "mother": "mother",
    "father": "father",
    "sibling": "sibling",
    "gc_content": "content",
    "public_name": "name",
    "cohort": "cohort",
    "storage_conditions": "conditions",
    "dna": {
        "pre_amplified": true,
        "date_of_sample_extraction": "2013-04-25 11:05 UTC",
        "extraction_method": "method",
        "concentration": 20,
        "sample_purified": false,
        "concentration_determined_by_which_method": "method"
    },
    "rna": {
        "pre_amplified": true,
        "date_of_sample_extraction": "2013-04-25 11:05 UTC",
        "extraction_method": "method",
        "concentration": 20,
        "sample_purified": false,
        "concentration_determined_by_which_method": "method"
    },
    "cellular_material": {
        "lysed": true
    },
    "genotyping": {
        "country_of_origin": "England",
        "geographical_region": "UK",
        "ethnicity": "English"
    }
}
< 200
< Content-Type: application/json
{
    "sample": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "sanger_sample_id": "studyX-1",
        "gender": "Male",
        "state": "published",
        "sample_type": "RNA",
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "storage_conditions": "conditions",
        "taxon_id": 9606,
        "volume": 100,
        "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "English"
        }
    }
}


**Delete a sample**

DELETE /11111111-2222-3333-4444-555555555555
> Accept: application/json
< 200
< Content-Type: application/json
{
    "sample": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "sanger_sample_id": "studyX-1",
        "gender": "Male",
        "state": "draft",
        "sample_type": "RNA",
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "storage_conditions": "conditions",
        "taxon_id": 9606,
        "volume": 100,
        "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25T11:05:00+00:00",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "English"
        }
    }
}


**Bulk create samples**

__FROM LIMS-MANAGEMENT-APP VERSION 2.0.1, BULK_CREATE_SAMPLE ACTION IS NOT AVAILABLE ANYMORE.
USE THE CREATE COLLECTION ACTION INSTEAD.__

* `quantity` and `sanger_sample_id_core` are mandatory
* If `state` is set to `published`, `taxon_id`, `scientific_name`, `common_name` and `supplier_sample_name` are mandatory
* If `taxon_id` is set, it must match with `scientific_name`/`common_name`
* If `sample_type` is set, it must belong to `DNA Human`, `DNA Pathogen`, `RNA`, `Blood`, `Saliva`, `Tissue Non-Tumour`, `Tissue Tumour`, `Pathogen` or `Cell Pellet`
* If `gender` is set, it must belong to `Not applicable`, `Male`, `Female`, `Mixed`, `Hermaphrodite` or `Unknown`

See the example below to know the list of available parameters for a sample.
POST /actions/bulk_create_sample
> Accept: application/json
{
    "bulk_create_sample": {
        "quantity": 3,
        "sanger_sample_id_core": "studyX",
        "state": "draft",
        "gender": "Male",
        "sample_type": "RNA",
        "taxon_id": 9606,
        "volume": 100,
        "date_of_sample_collection": "2013-04-25 10:27 UTC",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "storage_conditions": "conditions",
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:05 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:05 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "English"
        }
    }
}
< 200
< Content-Type: application/json
{
    "bulk_create_sample": {
        "actions": {
        },
        "user": "user",
        "application": "application",
        "result": {
            "samples": [
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "create": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "update": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
                    },
                    "uuid": "11111111-2222-3333-4444-555555555555",
                    "sanger_sample_id": "studyX-1",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 100,
                    "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false,
                    "dna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "rna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "cellular_material": {
                        "lysed": true
                    },
                    "genotyping": {
                        "country_of_origin": "England",
                        "geographical_region": "UK",
                        "ethnicity": "english"
                    }
                },
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                    },
                    "uuid": "11111111-2222-3333-4444-666666666666",
                    "sanger_sample_id": "studyX-2",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 100,
                    "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false,
                    "dna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "rna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "cellular_material": {
                        "lysed": true
                    },
                    "genotyping": {
                        "country_of_origin": "England",
                        "geographical_region": "UK",
                        "ethnicity": "english"
                    }
                },
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-777777777777",
                        "create": "http://example.org/11111111-2222-3333-4444-777777777777",
                        "update": "http://example.org/11111111-2222-3333-4444-777777777777",
                        "delete": "http://example.org/11111111-2222-3333-4444-777777777777"
                    },
                    "uuid": "11111111-2222-3333-4444-777777777777",
                    "sanger_sample_id": "studyX-3",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 100,
                    "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false,
                    "dna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "rna": {
                        "pre_amplified": true,
                        "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                        "extraction_method": "method",
                        "concentration": 20,
                        "sample_purified": false,
                        "concentration_determined_by_which_method": "method"
                    },
                    "cellular_material": {
                        "lysed": true
                    },
                    "genotyping": {
                        "country_of_origin": "England",
                        "geographical_region": "UK",
                        "ethnicity": "english"
                    }
                }
            ]
        },
        "quantity": 3,
        "state": "draft",
        "sanger_sample_id_core": "studyX",
        "taxon_id": 9606,
        "volume": 100,
        "date_of_sample_collection": "2013-04-25 10:27 UTC",
        "is_sample_a_control": true,
        "is_re_submitted_sample": false,
        "hmdmc_number": "number",
        "supplier_sample_name": "name",
        "common_name": "man",
        "scientific_name": "homo sapiens",
        "ebi_accession_number": "number",
        "sample_source": "source",
        "mother": "mother",
        "father": "father",
        "sibling": "sibling",
        "gc_content": "content",
        "public_name": "name",
        "cohort": "cohort",
        "storage_conditions": "conditions",
        "gender": "Male",
        "sample_type": "RNA",
        "dna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:10 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "rna": {
            "pre_amplified": true,
            "date_of_sample_extraction": "2013-04-25 11:10 UTC",
            "extraction_method": "method",
            "concentration": 20,
            "sample_purified": false,
            "concentration_determined_by_which_method": "method"
        },
        "cellular_material": {
            "lysed": true
        },
        "genotyping": {
            "country_of_origin": "England",
            "geographical_region": "UK",
            "ethnicity": "english"
        }
    }
}


**Bulk update samples**

* `by` must belong to `uuid`, `sanger_sample_id`. If `by` is null, it assumes uuids are used.
* `updates` is mandatory

See the example below to know the list of available parameters for a sample.
POST /actions/bulk_update_sample
> Accept: application/json
{
    "bulk_update_sample": {
        "by": "uuid",
        "updates": {
            "11111111-2222-3333-4444-555555555555": {"volume": 5000},
            "11111111-2222-3333-4444-666666666666": {"volume": 4000}
        }
    }
}
< 200
< Content-Type: application/json
{
    "bulk_update_sample": {
        "actions": {
        },
        "user": "user",
        "application": "application",
        "result": {
            "samples": [
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "create": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "update": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
                    },
                    "uuid": "11111111-2222-3333-4444-555555555555",
                    "sanger_sample_id": "studyX-1",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 5000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                },
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                    },
                    "uuid": "11111111-2222-3333-4444-666666666666",
                    "sanger_sample_id": "studyX-2",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 4000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                }
            ]
        },
        "by": "uuid",
        "updates": {
            "11111111-2222-3333-4444-555555555555": {"volume": 5000},
            "11111111-2222-3333-4444-666666666666": {"volume": 4000}
        }
    }
}


**Bulk delete samples**

* `sample_uuids` is mandatory

POST /actions/bulk_delete_sample
> Accept: application/json
{
    "bulk_delete_sample": {
        "sample_uuids": ["11111111-2222-3333-4444-555555555555", "11111111-2222-3333-4444-666666666666"]
    }
}
< 200
< Content-Type: application/json
{
    "bulk_delete_sample": {
        "actions": {
        },
        "user": "user",
        "application": "application",
        "result": {
            "samples": [
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "create": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "update": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
                    },
                    "uuid": "11111111-2222-3333-4444-555555555555",
                    "sanger_sample_id": "studyX-1",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 5000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                },
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                    },
                    "uuid": "11111111-2222-3333-4444-666666666666",
                    "sanger_sample_id": "studyX-2",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 5000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                }
            ]
        },
        "sample_uuids": [
            "11111111-2222-3333-4444-555555555555",
            "11111111-2222-3333-4444-666666666666"
        ],
        "sanger_sample_ids": null
    }
}


**Bulk delete samples by sanger sample IDs**

* `sanger_sample_ids` is mandatory

POST /actions/bulk_delete_sample
> Accept: application/json
{
    "bulk_delete_sample": {
        "sanger_sample_ids": ["S2-cd9b200ec5634288ad5b4f56eab2a84f", "S2-745819ae3dfe401caa68a87a90c95a4c"]
    }
}
< 200
< Content-Type: application/json
{
    "bulk_delete_sample": {
        "actions": {
        },
        "user": "user",
        "application": "application",
        "result": {
            "samples": [
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "create": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "update": "http://example.org/11111111-2222-3333-4444-555555555555",
                        "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
                    },
                    "uuid": "11111111-2222-3333-4444-555555555555",
                    "sanger_sample_id": "studyX-1",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 5000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                },
                {
                    "actions": {
                        "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                        "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                    },
                    "uuid": "11111111-2222-3333-4444-666666666666",
                    "sanger_sample_id": "studyX-2",
                    "state": "draft",
                    "gender": "Male",
                    "sample_type": "RNA",
                    "hmdmc_number": "number",
                    "supplier_sample_name": "name",
                    "common_name": "man",
                    "scientific_name": "Homo sapiens",
                    "ebi_accession_number": "number",
                    "sample_source": "source",
                    "mother": "mother",
                    "father": "father",
                    "sibling": "sibling",
                    "gc_content": "content",
                    "public_name": "name",
                    "cohort": "cohort",
                    "storage_conditions": "conditions",
                    "taxon_id": 9606,
                    "volume": 5000,
                    "date_of_sample_collection": "2013-04-25T11:27:00+01:00",
                    "is_sample_a_control": true,
                    "is_re_submitted_sample": false
                }
            ]
        },
        "sample_uuids": null,
        "sanger_sample_ids": ["S2-cd9b200ec5634288ad5b4f56eab2a84f", "S2-745819ae3dfe401caa68a87a90c95a4c"]
    }
}


--
Sample Collection Resource
--
**Create a new sample collection**

* `type` is mandatory
* `data` is an array containing hash. Each hash must follow the pattern `{'key': "key", 'value': "value", 'type': "type"}`. 
The supported types are `int`, `bool`, `string`, `uuid` and `url`. Note that `:type` is optional in the hash, the type being 
automatically deducted from the value if it is not explicitely set.
* `sample_uuids` the list of sample uuids to add in the sample collection

POST /sample_collections
> Accept: application/json
{
    "sample_collection": {
        "type": "Study",
        "data": [
            {"key": "key_string", "value": "value string", "type": "string"},
            {"key": "key_bool", "value": false},
            {"key": "key_int", "value": 123, "type": "int"},
            {"key": "key_url", "value": "http://www.example.org"},
            {"key": "key_uuid", "value": "11111111-1234-5678-9012-111111111111", "type": "uuid"}
        ],
        "sample_uuids": [
            "11111111-2222-3333-4444-666666666666", 
            "11111111-2222-3333-4444-777777777777"
        ]
    }
}
< 200
< Content-Type: application/json
{
    "sample_collection": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "type": "Study",
        "data": {
            "key_string": "value string",
            "key_bool": false,
            "key_uuid": "11111111-1234-5678-9012-111111111111",
            "key_url": "http://www.example.org",
            "key_int": 123
        },
        "samples": [
            {
                "actions": {
                    "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                },
                "uuid": "11111111-2222-3333-4444-666666666666",
                "state": null,
                "supplier_sample_name": null,
                "gender": "Male",
                "sanger_sample_id": "S2-1",
                "sample_type": "RNA",
                "scientific_name": "Homo sapiens",
                "common_name": "man",
                "hmdmc_number": null,
                "ebi_accession_number": null,
                "sample_source": null,
                "mother": null,
                "father": null,
                "sibling": null,
                "gc_content": null,
                "public_name": null,
                "cohort": null,
                "storage_conditions": null,
                "taxon_id": 9606,
                "volume": null,
                "date_of_sample_collection": null,
                "is_sample_a_control": null,
                "is_re_submitted_sample": null
            },
            {
               "actions": {
                 "read": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "create": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "update": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "delete": "http://example.org/11111111-2222-3333-4444-777777777777"
               },
               "uuid": "11111111-2222-3333-4444-777777777777",
               "state": null,
               "supplier_sample_name": null,
               "gender": "Male",
               "sanger_sample_id": "S2-2",
               "sample_type": "RNA",
               "scientific_name": "Homo sapiens",
               "common_name": "man",
               "hmdmc_number": null,
               "ebi_accession_number": null,
               "sample_source": null,
               "mother": null,
               "father": null,
               "sibling": null,
               "gc_content": null,
               "public_name": null,
               "cohort": null,
               "storage_conditions": null,
               "taxon_id": 9606,
               "volume": null,
               "date_of_sample_collection": null,
               "is_sample_a_control": null,
               "is_re_submitted_sample": null
             }
        ]
    }
}


**Create a new sample collection and bulk create samples**

* `type` is mandatory
* `data` is an array containing hash. Each hash must follow the pattern `{'key': "key", 'value': "value", 'type': "type"}`. 
The supported types are `int`, `bool`, `string`, `uuid` and `url`. Note that `:type` is optional in the hash, the type being 
automatically deducted from the value if it is not explicitely set.
* `samples` the parameters of the samples to create

POST /sample_collections
> Accept: application/json
{
    "sample_collection": {
        "type": "Study",
        "data": [
            {"key": "key_string", "value": "value string", "type": "string"},
            {"key": "key_bool", "value": false},
            {"key": "key_int", "value": 123, "type": "int"},
            {"key": "key_url", "value": "http://www.example.org"},
            {"key": "key_uuid", "value": "11111111-1234-5678-9012-111111111111", "type": "uuid"}
        ],
        "samples": {
            "sanger_sample_id_core": "S2",
            "quantity": 2,
            "gender": "Male",
            "sample_type": "RNA",
            "taxon_id": 9606,
            "volume": 100,
            "date_of_sample_collection": "2013-04-25 10:27 UTC",
            "is_sample_a_control": true,
            "is_re_submitted_sample": false,
            "hmdmc_number": "number",
            "supplier_sample_name": "name",
            "common_name": "man",
            "scientific_name": "homo sapiens",
            "ebi_accession_number": "number",
            "sample_source": "source",
            "mother": "mother",
            "father": "father",
            "sibling": "sibling",
            "gc_content": "content",
            "public_name": "name",
            "cohort": "cohort",
            "storage_conditions": "conditions",
            "dna": {
                "pre_amplified": true,
                "date_of_sample_extraction": "2013-04-25 11:10 UTC",
                "extraction_method": "method",
                "concentration": 20,
                "sample_purified": false,
                "concentration_determined_by_which_method": "method"
            },
            "rna": {
                "pre_amplified": true,
                "date_of_sample_extraction": "2013-04-25 11:10 UTC",
                "extraction_method": "method",
                "concentration": 20,
                "sample_purified": false,
                "concentration_determined_by_which_method": "method"
            },
            "cellular_material": {
                "lysed": true,
                "donor_id": "donor id"
            },
            "genotyping": {
                "country_of_origin": "England",
                "geographical_region": "UK",
                "ethnicity": "english"
            }
        }
    }
}
< 200
< Content-Type: application/json
{
    "sample_collection": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "type": "Study",
        "data": {
            "key_string": "value string",
            "key_bool": false,
            "key_uuid": "11111111-1234-5678-9012-111111111111",
            "key_url": "http://www.example.org",
            "key_int": 123
        },
        "samples": [
            {
                "actions": {
                    "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                },
                "uuid": "11111111-2222-3333-4444-666666666666",
                "state": "draft",
                "supplier_sample_name": "name",
                "gender": "Male",
                "sanger_sample_id": "S2-1",
                "sample_type": "RNA",
                "scientific_name": "homo sapiens",
                "common_name": "man",
                "hmdmc_number": "number",
                "ebi_accession_number": "number",
                "sample_source": "source",
                "mother": "mother",
                "father": "father",
                "sibling": "sibling",
                "gc_content": "content",
                "public_name": "name",
                "cohort": "cohort",
                "storage_conditions": "conditions",
                "taxon_id": 9606,
                "volume": 100,
                "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
                "is_sample_a_control": true,
                "is_re_submitted_sample": false,
                "dna": {
                    "pre_amplified": true,
                    "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                    "extraction_method": "method",
                    "concentration": 20,
                    "sample_purified": false,
                    "concentration_determined_by_which_method": "method"
                },
                "rna": {
                    "pre_amplified": true,
                    "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                    "extraction_method": "method",
                    "concentration": 20,
                    "sample_purified": false,
                    "concentration_determined_by_which_method": "method"
                },
                "cellular_material": {
                    "lysed": true,
                    "donor_id": "donor id"
                },
                "genotyping": {
                    "country_of_origin": "England",
                    "geographical_region": "UK",
                    "ethnicity": "english"
                }
            },
            {
                "actions": {
                    "read": "http://example.org/11111111-2222-3333-4444-777777777777",
                    "create": "http://example.org/11111111-2222-3333-4444-777777777777",
                    "update": "http://example.org/11111111-2222-3333-4444-777777777777",
                    "delete": "http://example.org/11111111-2222-3333-4444-777777777777"
                },
                "uuid": "11111111-2222-3333-4444-777777777777",
                "state": "draft",
                "supplier_sample_name": "name",
                "gender": "Male",
                "sanger_sample_id": "S2-2",
                "sample_type": "RNA",
                "scientific_name": "homo sapiens",
                "common_name": "man",
                "hmdmc_number": "number",
                "ebi_accession_number": "number",
                "sample_source": "source",
                "mother": "mother",
                "father": "father",
                "sibling": "sibling",
                "gc_content": "content",
                "public_name": "name",
                "cohort": "cohort",
                "storage_conditions": "conditions",
                "taxon_id": 9606,
                "volume": 100,
                "date_of_sample_collection": "2013-04-25T10:27:00+00:00",
                "is_sample_a_control": true,
                "is_re_submitted_sample": false,
                "dna": {
                    "pre_amplified": true,
                    "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                    "extraction_method": "method",
                    "concentration": 20,
                    "sample_purified": false,
                    "concentration_determined_by_which_method": "method"
                },
                "rna": {
                    "pre_amplified": true,
                    "date_of_sample_extraction": "2013-04-25T11:10:00+00:00",
                    "extraction_method": "method",
                    "concentration": 20,
                    "sample_purified": false,
                    "concentration_determined_by_which_method": "method"
                },
                "cellular_material": {
                    "lysed": true,
                    "donor_id": "donor id"
                },
                "genotyping": {
                    "country_of_origin": "England",
                    "geographical_region": "UK",
                    "ethnicity": "english"
                }
            }
        ]
    }
}


**Update a sample collection**

* `data` parameter is identical with the one in the sample collection create action
* `sample_uuids` the list of sample uuids in the sample collection. Note that it should reference all 
the samples in the collection and not only the ones to add. Passing an empty array to sample_uuids will
result removing all the samples from the sample collection.

PUT /11111111-2222-3333-4444-555555555555
> Accept: application/json
{
    "data": [
        {"key": "key_bool", "value": true},
        {"key": "key_string_2", "value": "new value", "type": "string"}
    ],
    "sample_uuids": [
        "11111111-2222-3333-4444-666666666666", 
        "11111111-2222-3333-4444-777777777777",
        "11111111-2222-3333-4444-888888888888"
    ]
}
< 200
< Content-Type: application/json
{
    "sample_collection": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "type": "Study",
        "data": {
            "key_string": "value string",
            "key_bool": true,
            "key_uuid": "11111111-1234-5678-9012-111111111111",
            "key_url": "http://www.example.org",
            "key_int": 123,
            "key_string_2": "new value"
        },
        "samples": [
            {
                "actions": {
                    "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                },
                "uuid": "11111111-2222-3333-4444-666666666666",
                "state": null,
                "supplier_sample_name": null,
                "gender": "Male",
                "sanger_sample_id": "S2-1",
                "sample_type": "RNA",
                "scientific_name": "Homo sapiens",
                "common_name": "man",
                "hmdmc_number": null,
                "ebi_accession_number": null,
                "sample_source": null,
                "mother": null,
                "father": null,
                "sibling": null,
                "gc_content": null,
                "public_name": null,
                "cohort": null,
                "storage_conditions": null,
                "taxon_id": 9606,
                "volume": null,
                "date_of_sample_collection": null,
                "is_sample_a_control": null,
                "is_re_submitted_sample": null
            },
            {
               "actions": {
                 "read": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "create": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "update": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "delete": "http://example.org/11111111-2222-3333-4444-777777777777"
               },
               "uuid": "11111111-2222-3333-4444-777777777777",
               "state": null,
               "supplier_sample_name": null,
               "gender": "Male",
               "sanger_sample_id": "S2-2",
               "sample_type": "RNA",
               "scientific_name": "Homo sapiens",
               "common_name": "man",
               "hmdmc_number": null,
               "ebi_accession_number": null,
               "sample_source": null,
               "mother": null,
               "father": null,
               "sibling": null,
               "gc_content": null,
               "public_name": null,
               "cohort": null,
               "storage_conditions": null,
               "taxon_id": 9606,
               "volume": null,
               "date_of_sample_collection": null,
               "is_sample_a_control": null,
               "is_re_submitted_sample": null
             },
             {
               "actions": {
                 "read": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "create": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "update": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "delete": "http://example.org/11111111-2222-3333-4444-888888888888"
               },
               "uuid": "11111111-2222-3333-4444-888888888888",
               "state": null,
               "supplier_sample_name": null,
               "gender": "Male",
               "sanger_sample_id": "S2-3",
               "sample_type": "RNA",
               "scientific_name": "Homo sapiens",
               "common_name": "man",
               "hmdmc_number": null,
               "ebi_accession_number": null,
               "sample_source": null,
               "mother": null,
               "father": null,
               "sibling": null,
               "gc_content": null,
               "public_name": null,
               "cohort": null,
               "storage_conditions": null,
               "taxon_id": 9606,
               "volume": null,
               "date_of_sample_collection": null,
               "is_sample_a_control": null,
               "is_re_submitted_sample": null
             }
        ]
    }
}


**Delete a sample collection**

DELETE /11111111-2222-3333-4444-555555555555
> Accept: application/json
< 200
< Content-Type: application/json
{
    "sample_collection": {
        "actions": {
            "read": "http://example.org/11111111-2222-3333-4444-555555555555",
            "create": "http://example.org/11111111-2222-3333-4444-555555555555",
            "update": "http://example.org/11111111-2222-3333-4444-555555555555",
            "delete": "http://example.org/11111111-2222-3333-4444-555555555555"
        },
        "uuid": "11111111-2222-3333-4444-555555555555",
        "type": "Study",
        "data": {
            "key_string": "value string",
            "key_bool": true,
            "key_uuid": "11111111-1234-5678-9012-111111111111",
            "key_url": "http://www.example.org",
            "key_int": 123,
            "key_string_2": "new value"
        },
        "samples": [
            {
                "actions": {
                    "read": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "create": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "update": "http://example.org/11111111-2222-3333-4444-666666666666",
                    "delete": "http://example.org/11111111-2222-3333-4444-666666666666"
                },
                "uuid": "11111111-2222-3333-4444-666666666666",
                "state": null,
                "supplier_sample_name": null,
                "gender": "Male",
                "sanger_sample_id": "S2-1",
                "sample_type": "RNA",
                "scientific_name": "Homo sapiens",
                "common_name": "man",
                "hmdmc_number": null,
                "ebi_accession_number": null,
                "sample_source": null,
                "mother": null,
                "father": null,
                "sibling": null,
                "gc_content": null,
                "public_name": null,
                "cohort": null,
                "storage_conditions": null,
                "taxon_id": 9606,
                "volume": null,
                "date_of_sample_collection": null,
                "is_sample_a_control": null,
                "is_re_submitted_sample": null
            },
            {
               "actions": {
                 "read": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "create": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "update": "http://example.org/11111111-2222-3333-4444-777777777777",
                 "delete": "http://example.org/11111111-2222-3333-4444-777777777777"
               },
               "uuid": "11111111-2222-3333-4444-777777777777",
               "state": null,
               "supplier_sample_name": null,
               "gender": "Male",
               "sanger_sample_id": "S2-2",
               "sample_type": "RNA",
               "scientific_name": "Homo sapiens",
               "common_name": "man",
               "hmdmc_number": null,
               "ebi_accession_number": null,
               "sample_source": null,
               "mother": null,
               "father": null,
               "sibling": null,
               "gc_content": null,
               "public_name": null,
               "cohort": null,
               "storage_conditions": null,
               "taxon_id": 9606,
               "volume": null,
               "date_of_sample_collection": null,
               "is_sample_a_control": null,
               "is_re_submitted_sample": null
             },
             {
               "actions": {
                 "read": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "create": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "update": "http://example.org/11111111-2222-3333-4444-888888888888",
                 "delete": "http://example.org/11111111-2222-3333-4444-888888888888"
               },
               "uuid": "11111111-2222-3333-4444-888888888888",
               "state": null,
               "supplier_sample_name": null,
               "gender": "Male",
               "sanger_sample_id": "S2-3",
               "sample_type": "RNA",
               "scientific_name": "Homo sapiens",
               "common_name": "man",
               "hmdmc_number": null,
               "ebi_accession_number": null,
               "sample_source": null,
               "mother": null,
               "father": null,
               "sibling": null,
               "gc_content": null,
               "public_name": null,
               "cohort": null,
               "storage_conditions": null,
               "taxon_id": 9606,
               "volume": null,
               "date_of_sample_collection": null,
               "is_sample_a_control": null,
               "is_re_submitted_sample": null
             }
        ]
    }
}


--
Searches
--

**Search for a sample collection by type and data**

The following search will get back all the sample collections which have a `Study` type and the 
parameter `key_bool` set to `true`, `key_string` set to `abcd` and `key_int` set to `1`.

POST /searches
> Accept: application/json
{
    "search": {
        "description": "search for a sample collection",
        "model": "sample_collection",
        "criteria": {
            "type": "Study",
            "data": {
                "key_bool": true,
                "key_string": "abcd",
                "key_int": 1
            }
        }
    }
}
< 200
< Content-Type: application/json
{
    "search": {
        "actions": {
            "read": "/11111111-2222-3333-4444-555555555555",
            "first": "/11111111-2222-3333-4444-555555555555/page=1",
            "last": "/11111111-2222-3333-4444-555555555555/page=-1"
        },
        "uuid": "11111111-2222-3333-4444-555555555555"
    }
}


**Search for a sample collection by type and sample uuids**

The following search will get back all the sample collections which have a `Study` type and contain
the sample `11111111-0000-0000-0000-111111111111` OR the sample `11111111-0000-0000-0000-222222222222`.

POST /searches
> Accept: application/json
{
    "search": {
        "description": "search for a sample collection",
        "model": "sample_collection",
        "criteria": {
            "type": "Study",
            "sample_uuids": [
                "11111111-0000-0000-0000-111111111111",
                "11111111-0000-0000-0000-222222222222"
            ]
        }
    }
}
< 200
< Content-Type: application/json
{
    "search": {
        "actions": {
            "read": "/11111111-2222-3333-4444-555555555555",
            "first": "/11111111-2222-3333-4444-555555555555/page=1",
            "last": "/11111111-2222-3333-4444-555555555555/page=-1"
        },
        "uuid": "11111111-2222-3333-4444-555555555555"
    }
}


**Search for samples by collection type and data**

The following search will get back all the samples which can be found in collections 
which have a `Study` type and the parameter `key_bool` set to `true`, `key_string` 
set to `abcd` and `key_int` set to `1`.

POST /searches
> Accept: application/json
{
    "search": {
        "description": "search for samples",
        "model": "sample",
        "criteria": {
            "sample_collection": {
                "type": "Study",
                "data": {
                    "key_bool": true,
                    "key_string": "abcd",
                    "key_int": 1
                }
            }
        }
    }
}
< 200
< Content-Type: application/json
{
    "search": {
        "actions": {
            "read": "/11111111-2222-3333-4444-555555555555",
            "first": "/11111111-2222-3333-4444-555555555555/page=1",
            "last": "/11111111-2222-3333-4444-555555555555/page=-1"
        },
        "uuid": "11111111-2222-3333-4444-555555555555"
    }
}


**Search for samples by collection uuids (intersection)**

The following search will get back all the samples which can be found in the collection 
`11111111-0000-0000-0000-111111111111` AND in the collection `11111111-0000-0000-0000-222222222222`.

POST /searches
> Accept: application/json
{
    "search": {
        "description": "search for samples in an intersection of collections",
        "model": "sample",
        "criteria": {
            "sample_collection": {
                "uuids_intersection": ["11111111-0000-0000-0000-111111111111", "11111111-0000-0000-0000-222222222222"]
            }
        }
    }
}
< 200
< Content-Type: application/json
{
    "search": {
        "actions": {
            "read": "/11111111-2222-3333-4444-555555555555",
            "first": "/11111111-2222-3333-4444-555555555555/page=1",
            "last": "/11111111-2222-3333-4444-555555555555/page=-1"
        },
        "uuid": "11111111-2222-3333-4444-555555555555"
    }
}